# Generated by Django 2.2.3 on 2019-07-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('inclusions', models.CharField(choices=[('meals', 'Meals'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='meals', max_length=30)),
                ('exclusions', models.CharField(choices=[('flight', 'Flight'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='flight', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('number_of_days', models.BigIntegerField(default=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('couple', 'Couple'), ('person', 'Person')], default='person', max_length=20)),
                ('review', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('destination', models.CharField(blank=True, max_length=30, null=True)),
                ('catergory', models.CharField(choices=[('family_holiday', 'Family Holiday'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='family_holiday', max_length=30)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Provider')),
            ],
        ),
    ]
