# Generated by Django 2.2.3 on 2019-07-18 12:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='inclusions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('meals', 'Meals'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='meals', max_length=27),
        ),
    ]
