# Generated by Django 2.2.3 on 2019-07-18 12:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20190718_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='catergory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('family_holiday', 'Family Holiday'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='family_holiday', max_length=30),
        ),
        migrations.AlterField(
            model_name='tour',
            name='exclusions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('flight', 'Flight'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='flight', max_length=30),
        ),
    ]
