# Generated by Django 2.2.3 on 2019-07-18 15:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20190718_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='catergory',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('family_holiday', 'Family Holiday'), ('road_trip', 'Road Trip'), ('natural_escape', 'Natural Escape')], default='family_holiday', max_length=39),
        ),
        migrations.AlterField(
            model_name='tour',
            name='inclusions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('meals', 'Meals'), ('flight', 'Flight'), ('bus', 'Bus'), ('sightseeing', 'Sightseeing'), ('hotel', 'Hotel')], default='meals', max_length=34),
        ),
    ]
